### ISSUE TITLE
Incompatibility with Botania's Endoflame

### ISSUE THREAD

**Issue by ThatSmartGuy21** [frank89722/Staaaaaaaaaaaack#8]
The endoflame eats a stack of coal instead of just one when stack sizes above 64 are present.

1. Place down an Endoflame
2. Throw two stacks of a flammable item on the ground next to it
3. It will consume a stack of items instead of just 1

**Expected behavior**
I expected the flower to reduce the total stack size by 1.

- MC version: [1.19.2]
- Mod version: [1.19.2-1.2-51]
- Loader: Fabric

Video:
https://github.com/frank89722/Staaaaaaaaaaaack/assets/88632676/423fe490-b16c-49cf-a16e-9127bcf39d86

Modlist: 
- Botania
- Fabric API
- Patchouli
- Staaaaaaaaaaaack
- Trinkets

**Comment by frank89722** [comment]
Thank you for the bug report but there is no easy(legit) fix on my end so could you also open an issue in their issue tracker?

Botania tries to sync the item entity by setting the item to EMPTY and then setting it back to the correct value, which I believe is an unnecessary move since they can achieve the same behavior by just setting it to a new copy of the item stack, and setting an item entity to EMPTY will trigger the refill process in Staaaaaaaaaaaack which cause this to happen.

**Comment by frank89722** [comment]
https://github.com/VazkiiMods/Botania/pull/4431

**Comment by frank89722** [comment]
Forget all I said above, I'm just suck at coding
Should be fixed in v1.4
Thanks for the report again!
